default:
  image: openjdk:11
  tags:
    - daloverflowrunner

stages:
  -build
  -test
  -deploy

maven-build:
  stage: build
  image: maven:latest
  scripts:
    -echo "Building the pipeline"
    - mvn clean package
  artifacts:
    paths:
      -target